version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=upvotedemocracy
      - POSTGRES_USER=upvotedemocracy
      - POSTGRES_PASSWORD=upvotedemocracy

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

